"""Compatibility paths for the bundled evaluation primitives."""

from __future__ import annotations

from lnp_agent.paths import DATA_DIR, PROJECT_ROOT, RESULTS_DIR, SOURCE_OF_TRUTH


VERSION_ROOT = PROJECT_ROOT
SOURCE_OF_TRUTH_RAW = SOURCE_OF_TRUTH
PLAN_DIR = PROJECT_ROOT / "docs"
SUMMARY_DIR = PROJECT_ROOT / "docs"
BENCHMARK_DIR = RESULTS_DIR / "benchmarks"
FIGURES_DIR = RESULTS_DIR / "figures"
DATA_DERIVED_DIR = RESULTS_DIR / "derived"
DATA_MANIFEST_DIR = RESULTS_DIR / "manifests"
TARGETING_DIR = RESULTS_DIR / "targeting"
CONFIGS_DIR = PROJECT_ROOT / "configs"
CODE_DIR = PROJECT_ROOT / "src"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
TESTS_DIR = PROJECT_ROOT / "tests"
RESULTS_CANDIDATES_DIR = RESULTS_DIR / "candidates"

DERIVED_CLEANED_BASIS = DATA_DERIVED_DIR / "cleaned_basis.csv"
DERIVED_SPLIT_MATRIX = DATA_DERIVED_DIR / "split_matrix.csv"
DERIVED_INTERIM_DATASET = DATA_DERIVED_DIR / "interim_dataset.csv"
DERIVED_OOF_PROPERTY_PREDICTIONS = DATA_DERIVED_DIR / "oof_property_predictions.csv"
DERIVED_OOF_ENDPOINT_PREDICTIONS = DATA_DERIVED_DIR / "oof_endpoint_predictions.csv"
DERIVED_STAGEWISE_OOF_PREDICTIONS = DATA_DERIVED_DIR / "stagewise_oof_predictions.csv"
DERIVED_CONFORMAL_PREDICTIONS = DATA_DERIVED_DIR / "conformal_predictions.csv"
OUT_DATA_AUDIT = DATA_DERIVED_DIR / "data_audit.csv"
BENCHMARK_DEPLOYABLE_BASELINE = BENCHMARK_DIR / "deployable_baseline.csv"
BENCHMARK_PROPERTY_HEADS = BENCHMARK_DIR / "property_heads.csv"
BENCHMARK_EXPLANATORY_AUDIT = BENCHMARK_DIR / "explanatory_audit.csv"
BENCHMARK_STAGEWISE_OOF = BENCHMARK_DIR / "stagewise_oof.csv"
BENCHMARK_MODEL_ZOO = BENCHMARK_DIR / "model_zoo.csv"
BENCHMARK_UNCERTAINTY_CI = BENCHMARK_DIR / "uncertainty_ci.csv"
BENCHMARK_CANDIDATE_SUMMARY = BENCHMARK_DIR / "candidate_summary.csv"
BENCHMARK_NP_RATIO_STRATIFIED = BENCHMARK_DIR / "np_ratio_stratified.csv"
BENCHMARK_LEAVE_TEMPLATE_OUT = BENCHMARK_DIR / "leave_template_out.csv"
BENCHMARK_CONFORMAL_DIAGNOSTICS = BENCHMARK_DIR / "conformal_diagnostics.csv"
DERIVED_CANDIDATE_PARETO = DATA_DERIVED_DIR / "candidate_pareto.csv"
MISSING_NP3_CELLS = RESULTS_CANDIDATES_DIR / "missing_design_cells.csv"
OUT_MANIFEST = DATA_MANIFEST_DIR / "run_manifest.json"
STAGEWISE_MANIFEST = DATA_MANIFEST_DIR / "stagewise_manifest.json"
OUT_SUMMARY = RESULTS_DIR / "summary.md"
OUT_SCOPE = RESULTS_DIR / "scope.md"
FIG_DEPLOYABLE_BASELINE = FIGURES_DIR / "deployable_baseline.png"
FIG_PROPERTY_HEADS = FIGURES_DIR / "property_heads.png"
FIG_EXPLANATORY_AUDIT = FIGURES_DIR / "explanatory_audit.png"
FIG_STAGEWISE_VS_BASELINE = FIGURES_DIR / "stagewise_vs_baseline.png"
FIG_DATA_STRUCTURE = FIGURES_DIR / "data_structure.png"
FIG_CV_SCHEME = FIGURES_DIR / "cross_validation_scheme.png"
FIG_MODEL_ZOO_COMPARISON = FIGURES_DIR / "model_zoo_comparison.png"
FIG_CANDIDATE_PARETO = FIGURES_DIR / "candidate_pareto.png"
FIG_NP_RATIO_STRATIFIED = FIGURES_DIR / "np_ratio_stratified.png"
FIG_CONFORMAL_COVERAGE = FIGURES_DIR / "conformal_coverage.png"
FIG_CONFORMAL_WIDTH = FIGURES_DIR / "conformal_interval_width.png"
FIG_MISSING_CELLS = FIGURES_DIR / "missing_design_cells.png"
TARGETING_ASSAY_TEMPLATE = TARGETING_DIR / "targeting_assay_template.csv"
TARGETING_JOINED = TARGETING_DIR / "targeting_joined.csv"
